### ISSUE TITLE
Time objects are unassigned - don't show up in timesheet view

### ISSUE THREAD

**Issue by Isuru-F** [ibigfoot/timesheeter#4]
Noticed the time I logged via the tool didn't show up in my timesheet view. Is there some way I can configure it always create time in my name?

**Steps to reproduce**
1. Log time via the plugin
2. Go into TaskRay -> Timesheet view 

Expected
- To see the time that I logged

Actual 
- Nothing shows up in timesheet view as the time object didn't have my name as the owner/team it's unassigned. 
- When I go to the project -> Task I can see the time logged (but without an owner) 

![image](https://user-images.githubusercontent.com/61958023/80671317-cded0900-8aec-11ea-9fa6-934f090350f7.png)

**Comment by troysellers** [comment]
Fix in place.. can you test?

**Comment by Isuru-F** [comment]
Didn't seem to come through for the ones after I updated the timezone on my profile. Need me to deploy from manifest? 

![image](https://user-images.githubusercontent.com/61958023/80783464-402d1e80-8bbd-11ea-966c-9d04e26474ce.png)
